version: "3.9"

services:
  # ========== MySQL Database ==========
  db:
    image: mysql:8.0
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: signal_db
      MYSQL_USER: signal_user
      MYSQL_PASSWORD: signal_pass
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped

  # ========== Signal-CLI REST API ==========
  signalcli:
    image: bbernhard/signal-cli-rest-api:0.90
    container_name: signalcli
    environment:
      # 若不需要自动轮询收信，可注释此行
      - AUTO_RECEIVE_SCHEDULE=*/5 * * * *
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: unless-stopped
    # 如果想持久化Signal-CLI数据, 可添加:
    # volumes:
    #   - ./signalcli-data:/home/.local/share/signal-cli

  # ========== Node.js 后端 ==========
  nodebackend:
    build: ./nodebackend # 指向 nodebackend/Dockerfile
    container_name: nodebackend
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_HOST: db
      DB_USER: signal_user
      DB_PASS: signal_pass
      DB_NAME: signal_db
      SIGNAL_CLI_URL: http://signalcli:8080
    depends_on:
      - db
      - signalcli
    restart: unless-stopped

  # ========== Nginx (反向代理) ==========
  nginx:
    image: nginx:stable
    container_name: mynginx
    depends_on:
      - nodebackend
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped

volumes:
  db_data:
